// <auto-generated />
using System;
using FlightTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightTracker.Data.Migrations
{
    [DbContext(typeof(FlightTrackerDbContext))]
    [Migration("20260210143838_AddTargetDateDestinations")]
    partial class AddTargetDateDestinations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("FlightTracker.Core.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirportCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirportCode")
                        .IsUnique();

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("FlightTracker.Core.Entities.PriceCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("EUR");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stops")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetDateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CheckTimestamp");

                    b.HasIndex("DestinationId");

                    b.HasIndex("TargetDateId", "DestinationId");

                    b.ToTable("PriceChecks");
                });

            modelBuilder.Entity("FlightTracker.Core.Entities.TargetDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OutboundDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OutboundDate", "ReturnDate")
                        .IsUnique();

                    b.ToTable("TargetDates");
                });

            modelBuilder.Entity("FlightTracker.Core.Entities.TargetDateDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetDateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("TargetDateId", "DestinationId")
                        .IsUnique();

                    b.ToTable("TargetDateDestinations");
                });

            modelBuilder.Entity("FlightTracker.Core.Entities.PriceCheck", b =>
                {
                    b.HasOne("FlightTracker.Core.Entities.Destination", "Destination")
                        .WithMany("PriceChecks")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightTracker.Core.Entities.TargetDate", "TargetDate")
                        .WithMany("PriceChecks")
                        .HasForeignKey("TargetDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("TargetDate");
                });

            modelBuilder.Entity("FlightTracker.Core.Entities.TargetDateDestination", b =>
                {
                    b.HasOne("FlightTracker.Core.Entities.Destination", "Destination")
                        .WithMany("TargetDateDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightTracker.Core.Entities.TargetDate", "TargetDate")
                        .WithMany("TargetDateDestinations")
                        .HasForeignKey("TargetDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("TargetDate");
                });

            modelBuilder.Entity("FlightTracker.Core.Entities.Destination", b =>
                {
                    b.Navigation("PriceChecks");

                    b.Navigation("TargetDateDestinations");
                });

            modelBuilder.Entity("FlightTracker.Core.Entities.TargetDate", b =>
                {
                    b.Navigation("PriceChecks");

                    b.Navigation("TargetDateDestinations");
                });
#pragma warning restore 612, 618
        }
    }
}
